name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@1.15
        with:
          remote-protocol: "sftp"
          remote-host: "ssh.strato.de"
          remote-user: "www.mvoberachern.de"
          remote-password: ${{ secrets.STRATO_MASTER }}
          remote-path: "/"